import Meals from '@/components/Meals'
import React from 'react'
export const metadata = {
  title: {
    absolute: "meals"
  },
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className='p-12'>
        <h1 className='text-3xl font-semibold text-red-400'>Choose your Meals</h1>
        <p>Choose meals of you meals searching...</p>
        <Meals />
    </div>
  )
}
export default page